title: Terceira Events
description: What's happening on Terceira Island
baseurl: ""
url: "https://terceiraevents.github.io"
timezone: Atlantic/Azores

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
